### PR TITLE
Add e2e specs for rails7

### PR DESCRIPTION
**Pull request by alisnic**
#28 

Here is how the completion coverage looks:

```
$ PRINT_STATS=true bundle exec rspec spec/solargraph-rails/rails7_spec.rb

...

{:class_name=>"ActionDispatch::Routing::Mapper", :total=>139, :covered=>126, :typed=>8, :percent_covered=>90.6, :percent_typed=>5.8}
{:class_name=>"ActiveJob::Base", :total=>183, :covered=>110, :typed=>8, :percent_covered=>60.1, :percent_typed=>4.4}
{:class_name=>"ActionController::Base", :total=>434, :covered=>147, :typed=>13, :percent_covered=>33.9, :percent_typed=>3.0}
{:class_name=>"Array", :total=>107, :covered=>105, :typed=>7, :percent_covered=>98.1, :percent_typed=>6.5}
{:class_name=>"Class", :total=>106, :covered=>102, :typed=>8, :percent_covered=>96.2, :percent_typed=>7.5}
{:class_name=>"Date", :total=>169, :covered=>167, :typed=>10, :percent_covered=>98.8, :percent_typed=>5.9}
{:class_name=>"DateTime", :total=>196, :covered=>121, :typed=>8, :percent_covered=>61.7, :percent_typed=>4.1}
{:class_name=>"File", :total=>88, :covered=>86, :typed=>8, :percent_covered=>97.7, :percent_typed=>9.1}
{:class_name=>"Hash", :total=>117, :covered=>115, :typed=>7, :percent_covered=>98.3, :percent_typed=>6.0}
{:class_name=>"Integer", :total=>108, :covered=>106, :typed=>8, :percent_covered=>98.1, :percent_typed=>7.4}
{:class_name=>"Kernel", :total=>55, :covered=>54, :typed=>4, :percent_covered=>98.2, :percent_typed=>7.3}
{:class_name=>"String", :total=>114, :covered=>112, :typed=>8, :percent_covered=>98.2, :percent_typed=>7.0}
{:class_name=>"Time", :total=>196, :covered=>192, :typed=>10, :percent_covered=>98.0, :percent_typed=>5.1}
{:class_name=>"ActiveRecord::Base", :total=>847, :covered=>334, :typed=>10, :percent_covered=>39.4, :percent_typed=>1.2}

...
```

### CODE REVIEW

**Comment by alisnic** [comment]
@iftheshoefritz can we try running the github workflow which I added in previous PR? Maybe it'll pass, who knows 🤔

**Comment by iftheshoefritz** [comment]
sounds good @alisnic :)

**Review by iftheshoefritz — APPROVED** [review]

**Comment by iftheshoefritz** [comment]
https://github.com/iftheshoefritz/solargraph-rails/pull/32 <- tiny change to ruby workflow. Sadly a bunch of the tests are failing.

**Comment by alisnic** [comment]
@iftheshoefritz oh well, I hoped. Let's merge then and we will tackle CI in a future PR?

**Comment by iftheshoefritz** [comment]
Go ahead

**Pull request merged**
