### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by grncdr**
These are patches I had made in solargraph-arc, but didn't upstream before it was merged with solargraph-rails.

I'm opening this PR to get feedback, and maybe some advice on testing.

### CODE REVIEW

**Comment by alisnic** [comment]
Thanks for the PR! Can you write some tests to reproduce the issues that you are trying to solve? There are a bunch of examples in the repo

**Comment by grncdr** [comment]
Sure, I will go back and add tests to each commit.

The last one I don't think I'll test explicitly, as it's a borign method extraction for a method that's called from many places.

**Comment by alisnic** [comment]
> The last one I don't think I'll test explicitly, as it's a boring method extraction for a method that's called from many places.

the last one is implementation detail, it's not supposed to be tested explicitly. If all tests work as intended, that means that as a consequence this method works as well

**Comment by grncdr** [comment]
I've gone back over this, and while adding tests I ended up combining all the table name related changes into one commit.

I ended up refactoring the walker/hook classes a little bit because I couldn't figure out why `walker.on :send, [:self, :table_name=, :str]` was not working. The real cause of that was fixed in https://github.com/iftheshoefritz/solargraph-rails/pull/40/commits/3c8e494a30b4edabaee504e22ae70668a1c1d5a1 but I felt like the other "cosmetic" changes are worth keeping.

Regarding the changes to table name inference, I think the commit message (and tests) explain it well enough, but there are still more ways to specify table prefixes that aren't supported yet. Some support was added in https://github.com/grncdr/solargraph-rails/commit/9dd555dd3f3431c509639e0600bcb271cf4569e6 (not included in this PR) but without control over the order Solargraph parses files, I don't think it can work.

**Comment by alisnic** [comment]
Excellent work!

**Pull request merged**
